archivo = open ("C:\\Users\\Persona Invitada\\Desktop\\1-2026-Fundamentos-Python-AlmanP\\class 06\\estudiantes.txt", "a")
Nombre = str(input("Ingrese su nombre"))
Carne = int(input("N. de carne"))
Nota = int (input("Nota final"))
archivo.write(f"{Nombre},{Carne},{Nota}")
archivo.close() 